version: "3"
services:
  airflow:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: airflow
    ports: 
      - 8081:8080
    volumes:
      - ./dags:/usr/local/airflow/dags